### ISSUE TITLE
Aggregate bonded transaction shows the deadline instead the Date when transaction is initiated

### ISSUE THREAD

**Issue by NikolaiB** [nemgrouplimited/symbol-desktop-wallet#1459]
![image](https://user-images.githubusercontent.com/11311924/116067224-c550f380-a6aa-11eb-84c2-0cc89834d54a.png)

**Comment by cryptoBeliever** [comment]
Date for regular transfer - OK
Date for hash lock - Wrong
Date for aggregate - Wrong

![image](https://user-images.githubusercontent.com/17684281/120901550-06d6a600-c63c-11eb-8b72-fb43b0198d2c.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever did you check https://github.com/nemgrouplimited/symbol-desktop-wallet/pull/1460?

**Comment by cryptoBeliever** [comment]
Yes. On branch gh1459-transaction-date
Now I checked again and is even stranger (for some transactions date is missing):

![image](https://user-images.githubusercontent.com/17684281/121020562-c5134000-c7a0-11eb-9308-95b0f1e58536.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever updated  `gh1459-transaction-date` branch, it should be working properly now.

**Comment by cryptoBeliever** [comment]
@bassemmagdy still wrong. Hash lock has the wrong date

![image](https://user-images.githubusercontent.com/17684281/121232044-71345400-c891-11eb-836e-c78442fcc02f.png)

**Comment by cryptoBeliever** [comment]
Now looks fine :+1:

**Comment by cryptoBeliever** [comment]
Fixed in integration branch.
