### ISSUE TITLE
Mosaic not added to mosaic list when created from aggregate

### ISSUE THREAD

**Issue by cryptoBeliever** [nemgrouplimited/symbol-desktop-wallet#723]
Steps:

1. Create account and go to aggregate tab.
2. Add namespace with random name to aggregate.
3. Add mosaic (without chaning any setting)
4. Init transaction and wait for confirmation.

Result: Namespace is visible on namespaces list but mosaic is not visible on mosaic list.

Example mosaic was added for this account (but it's not visible there):
http://explorer-0.10.0.x-01.symboldev.network/accounts/TDDWZAL7F552THJGMLC36MEL5ZR5V3LWRKMJWPY

This is mentioned mosaic:
http://explorer-0.10.0.x-01.symboldev.network/mosaics/698472BE5B102634

This is because mosaic is created without supply? Maybe we can add supply by flatting all transactions into aggregate (without nesting aggregate which is not possible)?

As I can see API is returning it:

http://api-01.us-west-1.0.10.0.x.symboldev.network:3000/mosaics?ownerAddress=TDDWZAL7F552THJGMLC36MEL5ZR5V3LWRKMJWPY

So I think it's filtered on explorer/wallet side.

**Comment by cryptoBeliever** [comment]
@yilmazbahadir I have some doubts if we can classify this as enhancement only.
Of course, when we assign supply during creating mosaic via aggregate then mosaic will show on the list but without it will be not visible. So we stay with a bug that mosaic is not visible on mosaics list and we can't assign supply.

**Comment by cryptoBeliever** [comment]
Changing to a bug because. We should either present mosaics without supply in mosaics list or allow add supply in aggregate feature.

**Comment by cryptoBeliever** [comment]
@bassemmagdy why it was dont in this way? Why we can't do same form for mosaic as is done for regular mosaic creation?

On this view are presented expired mosaics:
![image](https://user-images.githubusercontent.com/17684281/109866826-11ad2380-7c66-11eb-9df9-b6c0d61b088d.png)

**Comment by bassemmagdy** [comment]
@cryptoBeliever main issue which is mosaic with 0 balance not represented is solved, so that one should be closed if you verified it to avoid confusion, and we could open another issue as an enhancement to include mosaic supply in same transaction with mosaic creation.

**Comment by cryptoBeliever** [comment]
@bassemmagdy I'm still not able see mosaic created with aggregate in mosaics list. It should work?

**Comment by bassemmagdy** [comment]
Yes, as the problem was related to mosaic not being supply mutable which we now force in creating mosaics.

**Comment by cryptoBeliever** [comment]
Doesn't work for me.

**Comment by cryptoBeliever** [comment]
Maybe I used wrong version because now it works.
